### PR TITLE
Create JDK 21 fix .yml

### PR DESCRIPTION
**Pull request by kjjjjjjjjjjjj**
This is for fix JDK 21 and run it perfectly hope you like it sister

### CODE REVIEW

**Comment by WesleyVanNeck** [comment]
> This is for fix JDK 21 and run it perfectly hope you like it sister

Another useless spam commit

**Comment by Vera-Firefly** [comment]
> This is for fix JDK 21 and run it perfectly hope you like it sister

I think you need to learn about programming,this submission of yours is useless.

**Comment by kjjjjjjjjjjjj** [comment]
Sorry my misunderstanding which I trust on you sorry I trust on you about you take this and tell me there  are some fault in this code you need to supported with me you are my sister so I give you this

**Comment by kjjjjjjjjjjjj** [comment]
Sorry to say but if you help with it so give health not give negative comment

**Comment by kjjjjjjjjjjjj** [comment]
And yeah I understand I need to learn about coding but if you do help me so please do help me and please don't hurt me

**Comment by kjjjjjjjjjjjj** [comment]
> > This is for fix JDK 21 and run it perfectly hope you like it sister
> 
> Another useless spam commit

Oh hello take this self for you don't come in my arguments

**Comment by WesleyVanNeck** [comment]
> > This is for fix JDK 21 and run it perfectly hope you like it sister
> 
> I think you need to learn about programming,this submission of yours is useless.

Here even vera say so @kjjjjjjjjjjjj  go ahead pin me down with your issue

**Comment by kjjjjjjjjjjjj** [comment]
Do you please be personally talk with me because I have so many dramas

**Comment by kjjjjjjjjjjjj** [comment]
And please don't make me sad

**Comment by kjjjjjjjjjjjj** [comment]
> > > This is for fix JDK 21 and run it perfectly hope you like it sister
> > 
> > 
> > I think you need to learn about programming,this submission of yours is useless.
> 
> Here even vera say so @kjjjjjjjjjjjj go ahead pin me down with your issue

I need to friendship with you I need to the path of Chinese community of the developing apps I need to part with your Chinese community and I need to friendship with you and friendship with all Chinese your friends all Chinese sister and brothers I need to friendship and I have a no problem with you you have a problem with me tell me if you have any problem or any discussion with me so please tell me share your problem with me as a brother I understand your problems just tell me why you are so rude at me

**Comment by MovTery** [comment]
> > > > This is for fix JDK 21 and run it perfectly hope you like it sister
> > > 
> > > 
> > > I think you need to learn about programming,this submission of yours is useless.
> > 
> > 
> > Here even vera say so @kjjjjjjjjjjjj go ahead pin me down with your issue
> 
> I need to friendship with you I need to the path of Chinese community of the developing apps I need to part with your Chinese community and I need to friendship with you and friendship with all Chinese your friends all Chinese sister and brothers I need to friendship and I have a no problem with you you have a problem with me tell me if you have any problem or any discussion with me so please tell me share your problem with me as a brother I understand your problems just tell me why you are so rude at me

I know what you want to do, but I need you to understand one thing. The so-called "code" you wrote is actually invalid. I can't figure out what programming language it is. Instead, it seems more like a repetition of a paragraph. Do you think the program really understands what you've written? If you really like programming, then I suggest you understand and learn how to program properly instead of messing around by yourself. Of course, if you don't want to spend money on learning, you can also try self-study, such as searching for teaching videos on YouTube. I wish you can find the right path to learn programming and do what you want to do.

**Pull request closed without merging**
