### PR TITLE
Create Fixing Java

### PR DESCRIPTION
**Pull request by kjjjjjjjjjjjj**
There are some mistake in this code so I will fix it soon by the way this code for Java fixing

### CODE REVIEW

**Comment by kjjjjjjjjjjjj** [comment]
Thank you so much sister

**Comment by kjjjjjjjjjjjj** [comment]
Today I have a fever please kindly open the uploading so I can upload my files on this project

**Comment by Vera-Firefly** [comment]
You can submit PR again

---Original---
From: "x minecaaft ***@***.***&gt;
Date: Fri, Jan 26, 2024 19:49 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Vera-Firefly/PojavLauncher-Beta-Zink] Create Fixing Java (PR#112)




 
Today I have a fever please kindly open the uploading so I can upload my files on this project

**Comment by kjjjjjjjjjjjj** [comment]
Thank you sister
________________________________

**Comment by kjjjjjjjjjjjj** [comment]
Thank you sister

**Comment by kjjjjjjjjjjjj** [comment]
Can I give update

**Comment by kjjjjjjjjjjjj** [comment]
I give this launcher update can I uploaded it if you give me permission to upload it

**Pull request merged**
