### PR TITLE
Create Build.yml

### PR DESCRIPTION
**Pull request by kjjjjjjjjjjjj**

### CODE REVIEW

**Comment by Vera-Firefly** [comment]
What the fuck is this?

**Comment by kjjjjjjjjjjjj** [comment]
So far so good at least you are online today can we start new repository V2 because my coding experience is now is good so can we start a new new repository please can we start and please keep online and please answer me please please sister sister

**Comment by kjjjjjjjjjjjj** [comment]
Basically this file is made by me this file is build the Debug fixing file

**Comment by kjjjjjjjjjjjj** [comment]
Hello

**Comment by Vera-Firefly** [comment]
You should learn more about Github's build files

**Pull request closed without merging**
